name: CI build-test-pack
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release --logger trx --results-directory "TestResults"
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
          name: TestResults
          path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Pack
      run: dotnet pack --no-restore --no-build --configuration Release --version-suffix CI-$GITHUB_RUN_ID --output pkg
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
          name: ThumbHash-pkg
          path: pkg/*.*
